### ISSUE TITLE
hostNetwork?

### ISSUE THREAD

**Issue by utegental** [vidispine/hull#226]
Didn't found a way to set hostNetwork.

**Comment by gre9ory** [comment]
Hi @utegental,

you can set the `hostNetwork` as one of the [`pod:` properties](https://github.com/vidispine/hull/blob/main/hull/doc/objects_pod.md#the-hullpodv1-properties). 

As an concrete example, the following should do the trick for an example Deployment `myapp`:

```
hull:
  objects:
    deployment:
      myapp:
        pod:
          hostNetwork: true
          containers:
            app:
              ...
```

Some explanations following:

Any [workload based object instance](https://github.com/vidispine/hull#composing-objects-with-hull) includes the [`hull.PodTemplate.v1` schema](https://github.com/vidispine/hull/blob/main/hull/doc/objects_pod.md#the-hullpodtemplatev1-properties) which provides the `pod` field based on the [`hull.Pod.v1` schema](https://github.com/vidispine/hull/blob/main/hull/doc/objects_pod.md#the-hullpodv1-properties).

Within `hull.Pod.v1` you can work with the HULL based properties (here overwriting the Kubernetes objects properties):
```
initContainers
containers
volumes
```
however the documentation of `hull.Pod.v1` also points to  the Kubernetes API JSON schema for pods where you can find all the other original Kubernetes properties you can directly set on the `pod:` property (e.g. for Kubenretes 1.27 the [podspec-v1-core](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#podspec-v1-core)):
```
activeDeadlineSeconds
affinity
automountServiceAccountToken
...
hostNetwork
...
```

This is the composition idea of HULL. You can generally work with all existing Kubernetes properties on the object specifications. Only for particular aspects/properties HULL provides specific means of handling them (in a hopefully improved way). Here for the `pod:` specification it allows you to manage `containers`, `initContainers` and `volumes` as a dictionary to improve the merging of configuration layers instead of leaving them as arrays. On rendering everything is of course converted to Kubernetes spec conforming YAML. 

Hope this helps, if you need further assistance please let me know. Thanks!

**Comment by utegental** [comment]
@gre9ory, that is very helpful! I'm moving services from deprecated 'k8s-at-home' and from my first experience hull is very simple.
