### ISSUE TITLE
Is there an idiomatic way to access Chart and Release objects

### ISSUE THREAD

**Issue by eshepelyuk** [vidispine/hull#301]
Hello
 When using hull I need to access `.Chart` and `.Release` objects. Currently I am doing it like this 
 
 ```
tag: _HT!{{ (index . "$").Chart.Version }}
 ```
 
 Is there simpler/proper/idiomatic way of doing this ?

**Comment by Baum053** [comment]
Will try to get some time for this next week, definitly sounds like a good idea.

**Comment by eshepelyuk** [comment]
Thanks, folks.

**Comment by Baum053** [comment]
Wanted to give a little update since it is taking a bit longer.
First tests are looking good, probably we will introduce a notation like this

> _HT**Chart.Version

The problem we are currently fighting with is that the Chart object we get back sadly for some reasons has lowercase properties instead of uppercase:  https://helm.sh/docs/topics/charts/#the-chartyaml-file
This will probably end up confusing for a lot of people so we try to do it directly in a way that both cases work.

**Comment by eshepelyuk** [comment]
As helm docs saying
https://helm.sh/docs/topics/charts/#predefined-values
![Screenshot_2024-02-22-09-48-39-567.jpeg](https://github.com/vidispine/hull/assets/1279477/7ce423da-01b8-4b2f-9dad-813cc259aacb)

**Comment by Baum053** [comment]
Happy to announce we were finally able to release this feature.
It is now available in the newest releases 1.29.7, 1.28.6 and 1.27.15

We documentated it shortly here:
https://github.com/vidispine/hull/blob/main/hull/doc/transformations.md#get-chartrelease-informations
For more examples how it can be used you can check the section _test-get-transformation-on-root_ in our test file 
[main/hull/files/test/HULL/sources/cases/basic/basic.values.hull.yaml](https://github.com/vidispine/hull/tree/main/hull/files/test/HULL/sources/cases/basic/basic.values.hull.yaml)

**Comment by gre9ory** [comment]
Thanks @Baum053!
